<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Users.aspx.cs" Inherits="Hira.Users" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div style="margin-bottom:30px; margin-top:20px; margin-left:30px;">
        <img src="Content/Images/User.png" style="width:40px; height:40px;" />
        <asp:Label ID="lblMain" runat="server" Text="Users Management" CssClass="h3"></asp:Label>
    </div>
        
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" Width="811px" CssClass="table table-hover table-condensed" GridLines="Horizontal" BackColor="#F3F8F8" BorderStyle="None" ShowHeaderWhenEmpty="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Id" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing">
        <Columns>
            <asp:BoundField DataField="UserName" HeaderText="Username" />
            <asp:BoundField DataField="Email" HeaderText="Email" />
            <asp:CheckBoxField DataField="EmailConfirmed" HeaderText="Email Confirmed?" />
            <asp:BoundField DataField="PhoneNumber" HeaderText="Phone Number" />
            <asp:CheckBoxField DataField="PhoneNumberConfirmed" HeaderText="Phone Number confirmed?" />
            <asp:CheckBoxField DataField="TwoFactorEnabled" HeaderText="Two Factor Enabled?" />
        </Columns>
        <HeaderStyle BackColor="#DAE6EB" />
    </asp:GridView>
    <a href="EditUser.aspx?action=create" class="btn btn-default" style="background-color:#D7EBFF"> <img src="Content/Images/New.png" style="width:20px; height:20px;"/> Create New User </a>
</asp:Content>
